services:
  app:
    image: node:20-alpine
    depends_on:
      - api
    ports:
      - 8080:8080
    restart: unless-stopped
    working_dir: /home/node/frontend/
    command: sh -c "corepack enable && corepack prepare yarn@latest --activate && yarn install && yarn start"
    volumes:
      - ./frontend:/home/node/frontend
  api:
    image: node:20-alpine
    depends_on:
      - database
    ports:
      - 3000:3000
    restart: unless-stopped
    working_dir: /home/node/backend/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm start:dev"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/home/node/backend
  database:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - ./data:/data/db
    logging:
      driver: none
    env_file:
      - ./backend/.env

volumes:
  data:
