services:
  web:
    image: node:20-alpine
    depends_on:
      - database
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/app
      - ./.storybook:/home/node/app/.storybook
      - ./node_modules:/home/node/app/node_modules
    restart: unless-stopped
    working_dir: /home/node/app/
    command: sh -c "corepack enable &&4 corepack prepare pnpm@latest --activate && pnpm install && pnpm start:dev"
    env_file:
      - .env
  database:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - ./data:/data/db
    logging:
      driver: none
    env_file:
      - .env

volumes:
  data:
  .storybook:
  node_modules:
